// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.35.0
// source: ResourceManifest.proto

package mps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceManifest_StyleConfig_StyleID int32

const (
	ResourceManifest_StyleConfig__      ResourceManifest_StyleConfig_StyleID = 0
	ResourceManifest_StyleConfig_C3MM_1 ResourceManifest_StyleConfig_StyleID = 14
	ResourceManifest_StyleConfig_C3M    ResourceManifest_StyleConfig_StyleID = 15
	ResourceManifest_StyleConfig_DTM_1  ResourceManifest_StyleConfig_StyleID = 16
	ResourceManifest_StyleConfig_DTM_2  ResourceManifest_StyleConfig_StyleID = 17
	ResourceManifest_StyleConfig_C3MM_2 ResourceManifest_StyleConfig_StyleID = 52
)

// Enum value maps for ResourceManifest_StyleConfig_StyleID.
var (
	ResourceManifest_StyleConfig_StyleID_name = map[int32]string{
		0:  "_",
		14: "C3MM_1",
		15: "C3M",
		16: "DTM_1",
		17: "DTM_2",
		52: "C3MM_2",
	}
	ResourceManifest_StyleConfig_StyleID_value = map[string]int32{
		"_":      0,
		"C3MM_1": 14,
		"C3M":    15,
		"DTM_1":  16,
		"DTM_2":  17,
		"C3MM_2": 52,
	}
)

func (x ResourceManifest_StyleConfig_StyleID) Enum() *ResourceManifest_StyleConfig_StyleID {
	p := new(ResourceManifest_StyleConfig_StyleID)
	*p = x
	return p
}

func (x ResourceManifest_StyleConfig_StyleID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceManifest_StyleConfig_StyleID) Descriptor() protoreflect.EnumDescriptor {
	return file_ResourceManifest_proto_enumTypes[0].Descriptor()
}

func (ResourceManifest_StyleConfig_StyleID) Type() protoreflect.EnumType {
	return &file_ResourceManifest_proto_enumTypes[0]
}

func (x ResourceManifest_StyleConfig_StyleID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceManifest_StyleConfig_StyleID.Descriptor instead.
func (ResourceManifest_StyleConfig_StyleID) EnumDescriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0, 2, 0}
}

type ResourceManifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StyleConfig []*ResourceManifest_StyleConfig `protobuf:"bytes,2,rep,name=style_config,json=styleConfig,proto3" json:"style_config,omitempty"`
	TokenP2     string                          `protobuf:"bytes,30,opt,name=token_p2,json=tokenP2,proto3" json:"token_p2,omitempty"`
	// Historiquement la base URL des fichiers de cache (xml/altitude-*.xml)
	// etait ici, a la racine. Apple l'a depuis deplacee dans services.cache_base.
	// Conserve pour compatibilite avec les vieux manifestes.
	CacheBaseUrl string                        `protobuf:"bytes,31,opt,name=cache_base_url,json=cacheBaseUrl,proto3" json:"cache_base_url,omitempty"`
	CacheFile    []*ResourceManifest_CacheFile `protobuf:"bytes,72,rep,name=cache_file,json=cacheFile,proto3" json:"cache_file,omitempty"`
	CacheFile_2  []string                      `protobuf:"bytes,9,rep,name=cache_file_2,json=cacheFile2,proto3" json:"cache_file_2,omitempty"`
	// Conteneur d'endpoints de service ajoute par Apple.
	Services *ResourceManifest_Services `protobuf:"bytes,92,opt,name=services,proto3" json:"services,omitempty"`
}

func (x *ResourceManifest) Reset() {
	*x = ResourceManifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ResourceManifest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest) ProtoMessage() {}

func (x *ResourceManifest) ProtoReflect() protoreflect.Message {
	mi := &file_ResourceManifest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest.ProtoReflect.Descriptor instead.
func (*ResourceManifest) Descriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceManifest) GetStyleConfig() []*ResourceManifest_StyleConfig {
	if x != nil {
		return x.StyleConfig
	}
	return nil
}

func (x *ResourceManifest) GetTokenP2() string {
	if x != nil {
		return x.TokenP2
	}
	return ""
}

func (x *ResourceManifest) GetCacheBaseUrl() string {
	if x != nil {
		return x.CacheBaseUrl
	}
	return ""
}

func (x *ResourceManifest) GetCacheFile() []*ResourceManifest_CacheFile {
	if x != nil {
		return x.CacheFile
	}
	return nil
}

func (x *ResourceManifest) GetCacheFile_2() []string {
	if x != nil {
		return x.CacheFile_2
	}
	return nil
}

func (x *ResourceManifest) GetServices() *ResourceManifest_Services {
	if x != nil {
		return x.Services
	}
	return nil
}

type ResourceManifest_Services struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheBase *ResourceManifest_Services_Endpoint `protobuf:"bytes,2,opt,name=cache_base,json=cacheBase,proto3" json:"cache_base,omitempty"`
}

func (x *ResourceManifest_Services) Reset() {
	*x = ResourceManifest_Services{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ResourceManifest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManifest_Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest_Services) ProtoMessage() {}

func (x *ResourceManifest_Services) ProtoReflect() protoreflect.Message {
	mi := &file_ResourceManifest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest_Services.ProtoReflect.Descriptor instead.
func (*ResourceManifest_Services) Descriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResourceManifest_Services) GetCacheBase() *ResourceManifest_Services_Endpoint {
	if x != nil {
		return x.CacheBase
	}
	return nil
}

type ResourceManifest_CacheFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *ResourceManifest_CacheFile) Reset() {
	*x = ResourceManifest_CacheFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ResourceManifest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManifest_CacheFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest_CacheFile) ProtoMessage() {}

func (x *ResourceManifest_CacheFile) ProtoReflect() protoreflect.Message {
	mi := &file_ResourceManifest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest_CacheFile.ProtoReflect.Descriptor instead.
func (*ResourceManifest_CacheFile) Descriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResourceManifest_CacheFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ResourceManifest_StyleConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlPrefix_1 string                               `protobuf:"bytes,1,opt,name=url_prefix_1,json=urlPrefix1,proto3" json:"url_prefix_1,omitempty"`
	UrlPrefix_2 string                               `protobuf:"bytes,9,opt,name=url_prefix_2,json=urlPrefix2,proto3" json:"url_prefix_2,omitempty"`
	StyleId     ResourceManifest_StyleConfig_StyleID `protobuf:"varint,3,opt,name=style_id,json=styleId,proto3,enum=mps.ResourceManifest_StyleConfig_StyleID" json:"style_id,omitempty"`
}

func (x *ResourceManifest_StyleConfig) Reset() {
	*x = ResourceManifest_StyleConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ResourceManifest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManifest_StyleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest_StyleConfig) ProtoMessage() {}

func (x *ResourceManifest_StyleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ResourceManifest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest_StyleConfig.ProtoReflect.Descriptor instead.
func (*ResourceManifest_StyleConfig) Descriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ResourceManifest_StyleConfig) GetUrlPrefix_1() string {
	if x != nil {
		return x.UrlPrefix_1
	}
	return ""
}

func (x *ResourceManifest_StyleConfig) GetUrlPrefix_2() string {
	if x != nil {
		return x.UrlPrefix_2
	}
	return ""
}

func (x *ResourceManifest_StyleConfig) GetStyleId() ResourceManifest_StyleConfig_StyleID {
	if x != nil {
		return x.StyleId
	}
	return ResourceManifest_StyleConfig__
}

type ResourceManifest_Services_Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ResourceManifest_Services_Endpoint) Reset() {
	*x = ResourceManifest_Services_Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ResourceManifest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceManifest_Services_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest_Services_Endpoint) ProtoMessage() {}

func (x *ResourceManifest_Services_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_ResourceManifest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest_Services_Endpoint.ProtoReflect.Descriptor instead.
func (*ResourceManifest_Services_Endpoint) Descriptor() ([]byte, []int) {
	return file_ResourceManifest_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ResourceManifest_Services_Endpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_ResourceManifest_proto protoreflect.FileDescriptor

var file_ResourceManifest_proto_rawDesc = []byte{
	0x0a, 0x16, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x70, 0x73, 0x22, 0xb6, 0x05,
	0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x12, 0x44, 0x0a, 0x0c, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x70, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2e,
	0x53, 0x74, 0x79, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0b, 0x73, 0x74, 0x79,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x70, 0x32, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x50, 0x32, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x42, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x3e, 0x0a, 0x0a, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x48, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x6d, 0x70, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x09,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x32, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x61, 0x63, 0x68, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x32, 0x12, 0x3a, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x5c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6d, 0x70, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x69,
	0x66, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x70, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x0a, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x70, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x42, 0x61, 0x73, 0x65, 0x1a, 0x1c, 0x0a, 0x08, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x1a, 0x28, 0x0a, 0x09, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x1a, 0xe0, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x72, 0x6c, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x72, 0x6c, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x31, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x72, 0x6c, 0x5f, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x5f, 0x32, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x72, 0x6c,
	0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x32, 0x12, 0x44, 0x0a, 0x08, 0x73, 0x74, 0x79, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6d, 0x70, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74,
	0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x74, 0x79,
	0x6c, 0x65, 0x49, 0x44, 0x52, 0x07, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x47, 0x0a,
	0x07, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x05, 0x0a, 0x01, 0x5f, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x33, 0x4d, 0x4d, 0x5f, 0x31, 0x10, 0x0e, 0x12, 0x07, 0x0a, 0x03, 0x43,
	0x33, 0x4d, 0x10, 0x0f, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x54, 0x4d, 0x5f, 0x31, 0x10, 0x10, 0x12,
	0x09, 0x0a, 0x05, 0x44, 0x54, 0x4d, 0x5f, 0x32, 0x10, 0x11, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x33,
	0x4d, 0x4d, 0x5f, 0x32, 0x10, 0x34, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x74, 0x72, 0x6f, 0x70, 0x6c, 0x61, 0x73, 0x6d, 0x61,
	0x2f, 0x66, 0x6c, 0x79, 0x6f, 0x76, 0x65, 0x72, 0x2d, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x6d, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ResourceManifest_proto_rawDescOnce sync.Once
	file_ResourceManifest_proto_rawDescData = file_ResourceManifest_proto_rawDesc
)

func file_ResourceManifest_proto_rawDescGZIP() []byte {
	file_ResourceManifest_proto_rawDescOnce.Do(func() {
		file_ResourceManifest_proto_rawDescData = protoimpl.X.CompressGZIP(file_ResourceManifest_proto_rawDescData)
	})
	return file_ResourceManifest_proto_rawDescData
}

var file_ResourceManifest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ResourceManifest_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ResourceManifest_proto_goTypes = []interface{}{
	(ResourceManifest_StyleConfig_StyleID)(0),  // 0: mps.ResourceManifest.StyleConfig.StyleID
	(*ResourceManifest)(nil),                   // 1: mps.ResourceManifest
	(*ResourceManifest_Services)(nil),          // 2: mps.ResourceManifest.Services
	(*ResourceManifest_CacheFile)(nil),         // 3: mps.ResourceManifest.CacheFile
	(*ResourceManifest_StyleConfig)(nil),       // 4: mps.ResourceManifest.StyleConfig
	(*ResourceManifest_Services_Endpoint)(nil), // 5: mps.ResourceManifest.Services.Endpoint
}
var file_ResourceManifest_proto_depIdxs = []int32{
	4, // 0: mps.ResourceManifest.style_config:type_name -> mps.ResourceManifest.StyleConfig
	3, // 1: mps.ResourceManifest.cache_file:type_name -> mps.ResourceManifest.CacheFile
	2, // 2: mps.ResourceManifest.services:type_name -> mps.ResourceManifest.Services
	5, // 3: mps.ResourceManifest.Services.cache_base:type_name -> mps.ResourceManifest.Services.Endpoint
	0, // 4: mps.ResourceManifest.StyleConfig.style_id:type_name -> mps.ResourceManifest.StyleConfig.StyleID
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ResourceManifest_proto_init() }
func file_ResourceManifest_proto_init() {
	if File_ResourceManifest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ResourceManifest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ResourceManifest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManifest_Services); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ResourceManifest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManifest_CacheFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ResourceManifest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManifest_StyleConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ResourceManifest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceManifest_Services_Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ResourceManifest_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ResourceManifest_proto_goTypes,
		DependencyIndexes: file_ResourceManifest_proto_depIdxs,
		EnumInfos:         file_ResourceManifest_proto_enumTypes,
		MessageInfos:      file_ResourceManifest_proto_msgTypes,
	}.Build()
	File_ResourceManifest_proto = out.File
	file_ResourceManifest_proto_rawDesc = nil
	file_ResourceManifest_proto_goTypes = nil
	file_ResourceManifest_proto_depIdxs = nil
}
